name: Frontend Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-compose.test.yml"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"
  pull_request:
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-compose.test.yml"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Frontend Tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from frontend-test
